### ISSUE TITLE
inference issues

### ISSUE THREAD

**Issue by ArashHosseini** [bshao001/ChatLearner#10]
so training is done

**`# Finished epoch 60 @ step 37980 @ 2017-11-15 20:22:16. In the epoch, learning rate = 0.000096, mean loss = 0.3683, perplexity =   1.4453, and 552.35 seconds elapsed.`**

the evaluate part creating some reports, thanks for any help

```
flyn@tron:~/git/ChatLearner/chatbot$ python3.5 botui.py 
# Prepare dataset placeholder and hyper parameters ...
# Loading hparams from /home/flyn/git/ChatLearner/Data/Corpus/hparams.json ...
# Creating inference model ...
# Building graph for the model ...
# Restoring model weights ...
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/flyn/git/ChatLearner/Data/Result/basic
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2_4/_17 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_64_save/RestoreV2_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "botui.py", line 51, in <module>
    bot_ui()
  File "botui.py", line 32, in bot_ui
    result_dir=res_dir, result_file='basic')
  File "/home/flyn/git/ChatLearner/chatbot/botpredictor.py", line 48, in __init__
    self.model.saver.restore(session, os.path.join(result_dir, result_file))
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/flyn/git/ChatLearner/Data/Result/basic
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2_4/_17 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_64_save/RestoreV2_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save/RestoreV2', defined at:
  File "botui.py", line 51, in <module>
    bot_ui()
  File "botui.py", line 32, in bot_ui
    result_dir=res_dir, result_file='basic')
  File "/home/flyn/git/ChatLearner/chatbot/botpredictor.py", line 45, in __init__
    batch_input=self.infer_batch)
  File "/home/flyn/git/ChatLearner/chatbot/modelcreator.py", line 103, in __init__
    self.saver = tf.train.Saver(tf.global_variables())
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /home/flyn/git/ChatLearner/Data/Result/basic
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
	 [[Node: save/RestoreV2_4/_17 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_64_save/RestoreV2_4", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
```
that line makes me a little nervous

**`...Failed to find any matching files for /home/flyn/git/ChatLearner/Data/Result/basic`**

**Comment by ArashHosseini** [comment]
replace the basic in botui.py with the last train basic file was the solution for me

**Comment by ArashHosseini** [comment]
```
    with tf.Session() as sess:
        predictor = BotPredictor(sess, corpus_dir=corp_dir, knbase_dir=knbs_dir,
                                 result_dir=res_dir, result_file='basic-37980')
```
i did that basically, is this allowed and correct?

**Comment by bshao001** [comment]
@ArashHosseini That definitely works. However, I normally rename the files generated by the training because you don't have to use the last one always. You can try among files generated from epoch 56 to 60, and see if anyone gives you the best result. In Data\Test folder, there is a script testdemo.py. I normally run it can quickly scan the file it generates. You can modify samples.txt file if you want to add more questions or statements you like to try.

**Comment by ArashHosseini** [comment]
@bshao001 firstly great work, honestly. Thank you also for the support and help.
I will spend time into your tip and reference, i have also other different questions, but i will write them down and collect firstly. 
can i commit changes, i did for example this (and other changes....) 

```
    @staticmethod
    def get_number_plus(num1, num2):            
        ret_str = "{desc}{num1} + {num2} = {result}"
        desc = random.choice(FunctionData.easy_list)
        if not str_int_map.keys():
            res = num1 + num2
            return ret_str.format(desc = desc,
                                   num1 = num1,
                                   num2 = num2,
                                   result = res)

        if len(str_int_map.keys()) == 1:
            _index, txt_int = list(str_int_map.items())[0]
            if not _index:
                res = int(txt_int["int"]) + num2
                return "{0} or {1}".format(ret_str.format(desc = desc,
                                                           num1 = txt_int["txt"],
                                                           num2 = num2,
                                                           result = res),
                                           
                                           )
                
            res = int(txt_int["int"]) + num1
            return "{0} or {1}".format(ret_str.format(desc = desc,
                                                       num1 = num1,
                                                       num2 = txt_int["txt"],
                                                       result = res),
                                        FunctionData.int_to_en(res)
                                       )
        
        num1, num2 = zip(str_int_map.items())
        res = num1[0][1]["int"] + num2[0][1]["int"]
        return ret_str.format(desc = desc,
                              num1 = num1[0][1]["txt"],
                              num2 = num2[0][1]["txt"],
                              result = FunctionData.int_to_en(res))
```
which will create 
```
> Hey
Hey,
> how much is 10 + ten
Here you are: 10 + ten = 20 or twenty
> how much is ten + 20
ten + 20 = 30 or thirty
> how much is 10 + 10
That's simple, and I know how to solve it: 10 + 10 = 20
> how much is ten + twenty
Here is the result: ten + twenty = thirty
> 
```

**Comment by bshao001** [comment]
@ArashHosseini Thanks for the acknowledgment. I did not get your question. In case you are talking about licenses, yes, you can make whatever changes you want, and can use it for any purposes. I would really appreciate, if you can put a link to my project if you want to publish your work, especially when you are using Papaya data set, which I really spent sometime to create.

Feel free to ask any other technical questions when you have them.

**Comment by ArashHosseini** [comment]
@bshao001 i will definitely coming with some technical question in next time. Papaya Dataset is a great concept,i tested lot of different chatbots(torch, Keras and other tf repos) for a VR space experience, and i think i will go with yours. the chatbot would take the part of "CAMCOM"(housten), so the user can talk with it .....**audio>txt>chatbot>txt>audio**.You can see your work would be the core of the concept. 

- is there any way to change Papaya's age, i mean for the polite, patient, humorous and philosophical aspects, so using Papaya for the Housten Part?

**Comment by bshao001** [comment]
@ArashHosseini I had a plan to work on speech recognition as well so that it can really pronounce, but I have not yet get time for that.

If you want to change any information statically, you can just modify the training samples, and then train it again. If you want to produce his age based on this birth date, you can modify the responses of the age question with a function as we do for the arithmetic calculation. For example:

Q: How old are you?
A: _func_val_get_papaya_age .

Then in functiondata.py, you need to add a function called get_papaya_age(). Remember to add this function to func_dict in call_function method in the same file. This function will include the whole response sentence. You also have the option to place the desc part directly in the training response instead of having the whole thing in the function output.

**Comment by ArashHosseini** [comment]
- sounds great, i am now fully based on google(speech and nl api) for audio>txt, but  i am also looking for papers for the txt>audio part. So i am interested in both and if you have something i will evaluate it.
-its great to see the age modification workflow and i will do it, BUT I meant actually the mental age, is he bound by certain parameters that give him consciousness of a 9 year old? Is the only difference between a 20 year old Papaya for example and Papaya's present state only the age itself?

**Comment by bshao001** [comment]
@ArashHosseini Your concern makes sense, that's also why I decided to choose that type of age so that he can have excuse not to know something. It is not a big problem though. There are really some other training data associated with the age, such as going to elementary school and so on. Therefore, changing these key facts might trigger some kind of inconsistencies. If you really want to make everything consistent, that's kind of effort.

**Comment by ArashHosseini** [comment]
@bshao001 
> that's also why I decided to choose that type of age so that he can have excuse not to know something

makes sense. 
One the first chatbots which i tested was the agents of api.ai from google. the idea was to use the google assistant as "housten" in the game.You can train your agent and create behaviours based on triggers. 
I found out, your workflow is really similar to it. I exact searched for similar solutions without the endpoint on googles side. So you did that from my opinion. 
Imagine we would have a func called course_correction in the func assembly. 
the course_correction func looks like this and it need 2 param, which are position and rotation to calculate the new course. 

```
func course_correction(_param):
      if no parameter exists:
             ask user for rotation>
             ask user for position>
             compute
             return new_course
      if len.parameter = 1
            search for _param_1 in input
            ask user for _param_2>
            compute
            return new_course
      if len.parameter = 2
            compute
            return new_course
```
the training dataset would be something like,
```
Q: Housten, We need a course_correction! 
A: func_course_correction

Q:  Housten, course_correction please! 
A: func_course_correction

Q:  Housten, course_correction please! Are Rotation is _param
A: func_course_correction_param
```

 how you can see, it needs a exact planning but its give you a huge potential. I will go this week more into the code and will try to add a example with Papaya and the course_correction handler to dataset and train it. 

a question which i found really important to ask is the Name handling of the User, why we have not a simple user_handler func, to save the users name or information about the active user. And we could memorizing the name and other info over the whole chat lifetime.  

Q: my name is _param, what is my name?
A:func_name_handler_param

**Comment by bshao001** [comment]
@ArashHosseini You can try that. I did not do that because it is not easy to identify which word or words in a sentence is/are a name or names.

**Comment by bshao001** [comment]
@ArashHosseini Please open new issues to discuss if you have other questions. Closing this.
