### ISSUE TITLE
settings.py error

### ISSUE THREAD

**Issue by sushmas88** [bshao001/ChatLearner#11]
Hi @bshao001 ,
My stack comprises of:
Tensorflow-1.4
Python-3.5
CPU-8GB RAM
Pycharm IDE-2017.
NLTK-3.2.5

I'm trying to use your [pre-trained model](https://drive.google.com/file/d/1BUK9r_WV8z4FWZvN2lpvvluRmHjtoSLt/view) while running it I'm facing error like
 from settings import PROJECT_ROOT
ImportError: No module named 'settings'

Can you please resolve my issue as early as possible.
Thanks in advance.

**Comment by ArashHosseini** [comment]
Hey, 
did you miss to set the PYTHONPATH, if yes then

`gedit ~/.bashrc`

add following line and save 

`PYTHONPATH = /home/path/to/ChatLearner`

then reload 

`source ~/.bashrc`

**Comment by bshao001** [comment]
@ArashHosseini Thank you for helping me to answer the question.
@sushmas88 As explained, if you run it in a command line, please set up the environment variable PYTHONPATH. If you run it in PyCharm, try to use new project to create a project first. Hope this helps.

**Comment by sushmas88** [comment]
@bshao001.
@ArashHosseini 
Thanks.Your p retrained model is working.You haven't mentioned how to restore the model in the middle of training,How to use the checkpoints for check the functioning of the bot in the middle of training.How to use your p retrained model on my own data set i.e (re-training).

**Comment by bshao001** [comment]
@sushmas88 As far as I know, there is no good way to automatically evaluate a model. You may have to run it and check the chatbot responses manually. 

I don't think transfer learning can be applied in this model. I even carefully called it "trained model" instead of "pre-trained model" in Readme. If you do know any approach, please let me know. If you have your own training data, you can put together the training samples following the same format, and then run vocabgenerator.py to create the new vocab.txt. Finally you have to train the model from scratch.

**Comment by sushmas88** [comment]
Hi @bshao001 
 @ArashHosseini ,
   I cnfigured number of epochs as 60 and started training, and in modelcreator.py file, i have mentioned as-
    self.saver = tf.train.Saver(tf.global_variables(),max_to_keep=None)  to save checkpoint for every epoch, but in my case only event file is generating and checkpoints are not created for every epoch. 
while training, it is taking step size as 633 can you please justify why it is taking 633 as step size

Can you resolve my issue and tell me how to save checkpoint for each epoch

**Comment by bshao001** [comment]
@sushmas88 At line 99 of bottrainer.py, you should find something like this:

    if train_perp < 1.6 and train_perp < last_record_perp:

Remove this line, you should be able to save checkpoint for each epoch. Note that each checkpoint is about 1.6 GB, therefore, you should have enough disk space and expect more time due to this change.

**Comment by bshao001** [comment]
@sushmas88 Please open a new issue if you have other questions. If you feel this project is useful to you, please consider starring it.
