### ISSUE TITLE
Attention Mechanism

### ISSUE THREAD

**Issue by ArashHosseini** [bshao001/ChatLearner#18]
Hey @bshao001,
can you please, tell me a little about the **Attention Mechanism**, i saw the implementation on the nmt site.
Thanks

**Comment by bshao001** [comment]
@ArashHosseini It is a little complicated to understand and explain the attention mechanism. I can only give you an intuitive idea of the attention mechanism in the NMT model. It is used in other context though.

For the seq2seq model, without attention mechanism, the decoder can only generate output at each time step based on a fixed-length vector generated by the encoder and the previous outputs of the decoder. With the help of attention mechanism, the decoder can look at the input sentence (question) selectively based on the learned weights. With attention mechanism, the model can learn not only the mapping (relationship) of the question input as a whole to the answer output, but also other internal relationships. For example, it may very likely be able to learn these relationships:

1. who in the question -> a person (name) in the answer
2. How much or how many in the question -> a number in the answer.

The order to feed the input becomes less important with attention mechanism (whether to reverse the input), and so on.

If you really want to get some hands-on experience, I suggest you use a small training data set, such as 2000 to 5000 pairs of conversations, and then train this model with and without the attention mechanism, and see if that makes any differences. You might need to manually tweak some training samples to understand what you want.

Please share you findings if you do perform such an experiment. Thanks.

**Comment by ArashHosseini** [comment]
@bshao001  i found your example is really helpful, i will continue reading more about it......you have awakened my hunger, thanks a lot, will close this but post the diff between with(out)  attention mechanisms. .
