### ISSUE TITLE
Increase in dataset 

### ISSUE THREAD

**Issue by abhishekkritarth** [bshao001/ChatLearner#19]
@bshao001
Hi we have increased the dataset size by including open-subtitles dataset.We have preprocessed the dataset.We have problem in generating vocabulary.
How can i make changes such the bot initiates a conversation by saying hello...
Kindly help me in solving this issue.

**Comment by bshao001** [comment]
@abhishekkritarth Don't try to let the NN model to initiate a statement. Instead, this type of function can be easily implemented in the UI side.
