### ISSUE TITLE
A question about implicit module imports

### ISSUE THREAD

**Issue by saitbnzl** [bshao001/ChatLearner#2]
This line doesn't work for me in basicmodel.py:
`from chatbot.tfcopy.seq2seq import embedding_attention_seq2seq`

I'm having `No module named 'chatbot'` with Python 3.5.2 Because basicmodel.py is already in ./chatbot directory. Does not it have to be like this:
`from tfcopy.seq2seq import embedding_attention_seq2seq`

I've realized you do that everywhere. So I'm sure there is something that I don't know but Google didn't work this time. Can you please explain this or give me a link about that?

**Comment by bshao001** [comment]
Do you have an environment variable PYTHONPATH setup? I ran this in Windows, and if the project root is C:\Python\ChatLearner, I set PYTHONPATH to be: C:\Python\ChatLearner. This way, any relative module import (modules inside this project) should work.

**Comment by saitbnzl** [comment]
Thank you.
