### ISSUE TITLE
webui for ubuntu

### ISSUE THREAD

**Issue by abhishekkritarth** [bshao001/ChatLearner#20]
@bshao001 
We have followed the same procedure for Ubuntu.I have installed tornado from Pycharm Edition and Tomcat from ubuntu terminal.We are not getting response for it.I didnt understand how the Tomcat-client sending request to Tornado Server.i didn't understand  how tornado server contacting client internally.

Please solve my issue as soon as possible

Thanks in advance

**Comment by bshao001** [comment]
@abhishekkritarth 
If you want me to help troubleshooting the problem, please provide more details. If you are not familiar with SOAP protocol or if that is not your preference, please try webui_alternative, which is based on REST API. It is simpler to most people. BTW, if you think this ChatLearner project is helpful or useful to you, please acknowledging it by starring or forking it. Thanks.
