### ISSUE TITLE
What should i do extra effort to certain modify Conversation?

### ISSUE THREAD

**Issue by sushant097** [bshao001/ChatLearner#21]
If I changed any line of `a_papaya_new.txt` Should, i also should changed in `vocab.txt`.
I want to slighlty modified the conversion in my way where the bot can interact. 
**Please mention** how to make the new rule and make possible to change contents of that file before training.
Let's I change; Dialogue of `a_papaya_new.txt` as,
```
Q: What is your name? ----> Q: What is your name?
A: My name is Papaya. ----->A: My name is AI-Chatbot
```
**and several others.**
      > I am Strange by knowing how every word are linked to `vocab.txt` and  Tensorflow finds out the pattern between the input and trained datas and it worked.
Also, How can I ` papaya, Corpus, Reddit data-set` whole used to train my bot.
I deep look on it and not found any ideas on it.
Please ! clarify me.
Thanks in advance.

**Comment by bshao001** [comment]
@sushant097 
Yes, whenever you make any changes to any training samples (like modifying a_papaya_new.txt file), you should re-generate vocab.txt by running vocabgenerator.py in Corpus folder.

Concerning your second questions, here is the answer: the input and output of the NMT model are both integers (IDs), or the sequence number in vocab.txt. For example, the first word (line) in the vocab.txt (_unk_) is ID 0, the second (_bos_) is ID 1, and so on. Therefore, at the time of training and prediction, you need to maintain the same word to integer mapping, and integer to word mapping.

I could not figure out the meaning of your last question. If you still encounter any other issues, feel free to let me know. Thanks.

**Comment by sushant097** [comment]
@bshao001 
Thanks. Is vocab.txt contains the Reddit data-set and Corpus dialogue too .

**Comment by bshao001** [comment]
@sushant097 
Yes, the existing vocab.txt was generated using vocabgenerator.py, which reads all files in the three folders: Augment0, Augment1, and Augment2. Check the script of vocabgenerator.py. It is really straightforward. Please let me know if you have other questions.
