### ISSUE TITLE
SyntaxError: Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by mrmrn** [bshao001/ChatLearner#22]
hello.
I have an error here and it seems chatbot package cause it. how can I run bottrainer.py?
```
marn@mint18 ~/c/C/chatbot> python3 bottrainer.py 
Traceback (most recent call last):
  File "bottrainer.py", line 20, in <module>
    from chatbot.tokenizeddata import TokenizedData
  File "/usr/local/lib/python3.5/dist-packages/chatbot.py", line 166
    print 'Couldn\'t log in: Quitting.'
                                      ^
SyntaxError: Missing parentheses in call to 'print'
marn@mint18 ~/c/C/chatbot> pip3 install chatbot --upgrade
Requirement already up-to-date: chatbot in /usr/local/lib/python3.5/dist-packages

```

**Comment by bshao001** [comment]
@mrmrn Looks like you did not have the env variable PYTHONPATH set up. Please refer to the Before You Proceed section in the README, or early issues for details.

**Comment by mrmrn** [comment]
> export PYTHONPATH=$PYTHONPATH:/home/code/ChatLearner/   

I used it but it gaves me the same error.

**Comment by bshao001** [comment]
@mrmrn Unfortunately, this env seems only support one value, in other words, if you have multiple projects, you can point it to one. 

From what the error message indicates, it is looking for something not intended. chabot is a folder or a package. The compiler misunderstood it and was using something from your installed python 3.5 package.

**Comment by khritish29** [comment]
Traceback (most recent call last):
  File "botui.py", line 20, in <module>
    from chatbot.botpredictor import BotPredictor
  File "C:\Users\user1\miniconda3\envs\tensor1.4\lib\site-packages\chatbot.py", line 166
    print 'Couldn\'t log in: Quitting.'
                                      ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print('Couldn\'t log in: Quitting.')?



Hello i am getting this error what need to be do?
please help
