### ISSUE TITLE
How to run with gpu?

### ISSUE THREAD

**Issue by alialrabi** [bshao001/ChatLearner#26]
I have installed cud using  https://yangcha.github.io/GTX-1080/ ,then trying to run but still work with cpu not gpu,How to run with gpu?

**Comment by bshao001** [comment]
@alialrabi

You don't need to do anything special for this project to run using GPU(s). So after you installed TensorFlow-GPU, and try to run a TF session, did you see the GPU device(s) in the print outs? If the devices show, what error message do you get when you run this project with training or prediction?
