### ISSUE TITLE
Import error

### ISSUE THREAD

**Issue by diaprogrammer34** [bshao001/ChatLearner#29]
I’ve been trying to run bottrainer.py, but whenever i try i get this error:

Traceback (most recent call last):
  File "chatbot/bottrainer.py", line 20, in <module>
    from chatbot.tokenizeddata import TokenizedData
ImportError: No module named chatbot.tokenizeddata

Any ideas?

**Comment by bshao001** [comment]
@diaprogrammer34 
Please make sure you have the environment variable PYTHONPATH setup. Check README or early issues for details if you are not sure what this is about.

**Comment by diaprogrammer34** [comment]
I’ve set the PYTHONPATH variable to what is needed, yet it’s still returning the same error

**Comment by bshao001** [comment]
@diaprogrammer34 
That is not supposed to happen. Which OS are you using? What value of PYTHONPATH is there? Can you try to run some other python files in the same folder, just to see if any other can work?

**Comment by diaprogrammer34** [comment]
My OS is Linux LTS 14, the PYTHONPATH value is /home/liamtannock/ChatLearner and nothing else works, no

**Comment by diaprogrammer34** [comment]
where MYUSERNAME is my username, not literally MYUSERNAME

**Comment by bshao001** [comment]
@diaprogrammer34 
I am not sure why, but just try an alternative approach. Insert the following two lines into the beginning of each file that needs this type of import:

    import sys
    if "../" not in sys.path:
        sys.path.append("../") 

And see if that can help.

**Comment by diaprogrammer34** [comment]
That didnt work either :/

**Comment by bshao001** [comment]
One last thing you can try is to move all files in /chatbot folder one level up (to the project root folder), and then change all import statements in those files by removing "chatbot.".

**Comment by diaprogrammer34** [comment]
Thanks! That worked! But now i’m Getting a new error, whenever i run, this happens:

`terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)`

**Comment by bshao001** [comment]
@diaprogrammer34 
The fix suggests, to certain extent, that there is some kind of conflict in your python and/or TensorFlow environment. The new error may also be related. If you are seriously considering continue to work on this, please try to reinstall your whole python environment, also, please show your support to my project by starring and/or forking it, if you could. Thank you!

**Comment by diaprogrammer34** [comment]
had to change a few things in hparams so that my pc could handle it, and it now works, thanks for your help though!
