### ISSUE TITLE
[Question] Understanding flow to train model with custom data

### ISSUE THREAD

**Issue by samposin** [bshao001/ChatLearner#31]
Hello!
Great Repository!

I am trying to train model with custom data, i read one help reagrding this in which i came to know that we need to regenrate vocab.txt by running vocabgenerator.py in Corpus folder.
So my questions are:

1. When we run bottrainer.py, does this program just lookup for vocab.txt and not text files?
2. I looked a little into code it is looking for corpus directory then how data from "KnowledgeBase" folder is taken?

I am new to tensorflow nmt model, as i understand 
1. We have collection of text files with series of questions/answers, 
2. Then we converted those text files in the format so that our model can understand as vocab.txt 
3. Then when we train, program looks for vocab.txt and generate files in result folder that are used by chat program.

Please ! clarify me.
Thanks in advance.

**Comment by bshao001** [comment]
The NMT model takes integers/numbers as its input and output, it has no idea of the meaning of any words you see. File vocab.txt helps the program (not the model itself) to perform the conversion: at training time, words in each conversational pairs are converted to integers to feed the model; at inference time, words in the questions are converted to integers using the same vocab.txt, the model outputs numbers/integers, and the program converts them into human readable words.

KnowledgeBase is an add-on feature, which does not belong to the model itself. It is only used in prediction.

**Comment by samposin** [comment]
Ok got it, thank you very much for information.
