### ISSUE TITLE
Embeddings-question

### ISSUE THREAD

**Issue by ArashHosseini** [bshao001/ChatLearner#32]
Hey, 
can you please tell me where the embeddings happens in code, or are you using trained embeddings? 
thx

**Comment by bshao001** [comment]
@ArashHosseini 
It is not using any pre-trained embedding. Instead embedding is generated based on the training data set (Papaya data set). Embedding is used in both training and inference, and both the encoder and decoder. You can search the word "embedding" in file https://github.com/bshao001/ChatLearner/blob/master/chatbot/modelcreator.py, for details.
