### ISSUE TITLE
NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /var/www/html/python_ai/ChatLearner/Data/Result/basic

### ISSUE THREAD

**Issue by dineshobjects** [bshao001/ChatLearner#33]
NotFoundError (see above for traceback): Unsuccessful TensorSliceReader constructor: Failed to find any matching files for /var/www/html/python_ai/ChatLearner/Data/Result/basic
	 [[Node: save/RestoreV2 = RestoreV2[dtypes=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Please suggest something.

**Comment by bshao001** [comment]
@dineshobjects 
Please rename the files (the files generated by the trainer in /Data/Result) folder to basic.***, by removing the step numbers.

**Comment by dineshobjects** [comment]
@bshao001 
Thank you for the reply.
I run training for 1 day and there is no basic file generated. There is only train_log folder in result folder.
Should I rename train_log folder to basic? Please suggest.
Thank you!

**Comment by bshao001** [comment]
@dineshobjects 
You can either train longer or modify the code to let the models be saved sooner. Check issue #12 for details.
