### ISSUE TITLE
ModuleNotFoundError: No module named 'chatbot'

### ISSUE THREAD

**Issue by tmlahmed** [bshao001/ChatLearner#36]
I'm getting this error..
` File "D:/Python Chatbot/ChatLearner-master/chatbot/botui.py", line 20, in <module>
    from chatbot.botpredictor import BotPredictor
ModuleNotFoundError: No module named 'chatbot' `

**Comment by bshao001** [comment]
Do you have an environment variable PYTHONPATH setup? I ran this in Windows, and if the project root is C:\Python\ChatLearner, I set PYTHONPATH to be: C:\Python\ChatLearner. This way, any relative module import (modules inside this project) should work.

**Comment by tmlahmed** [comment]
Thanks. That problem is solved.
Now I'm getting a new error :(
I'm using your trained file and copied to 'Data' folder. When I run `botui.py` I'm getting this error.

`D:\Chatbot\ChatLearner\chatbot>python botui.py

# Prepare dataset placeholder and hyper parameters ...
Traceback (most recent call last):
  File "botui.py", line 53, in <module>
    bot_ui()
  File "botui.py", line 32, in bot_ui
    result_dir=res_dir, result_file='basic')
  File "D:\Chatbot\ChatLearner\chatbot\botpredictor.py", line 44, in __init__
    tokenized_data = TokenizedData(corpus_dir=corpus_dir, training=False)
  File "D:\Chatbot\ChatLearner\chatbot\tokenizeddata.py", line 50, in __init__
    self.src_max_len = self.hparams.src_max_len
AttributeError: 'NoneType' object has no attribute 'src_max_len' `

**Comment by bshao001** [comment]
I haven't seen this issue personally before. However, a similar issue was reported in #4. Please refer it.
