### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by AlexanderYogurt** [bshao001/ChatLearner#4]
`chatbot/tokenizeddata.py",` line 55, in __init__
    self.src_max_len = self.hparams.src_max_len

`AttributeError: 'NoneType' object has no attribute 'src_max_len'`

**Comment by AlexanderYogurt** [comment]
It turns out to be os.path issue. The tokenizeddata.py is in chatbot/ which will give the wrong PROJECT_PATH

**Comment by amitguptadumka** [comment]
@AlexanderYogurt so whats the solution to this?

**Comment by jaiaravind4u** [comment]
Whats is the solution to fix the problem?

**Comment by khritish29** [comment]
Any solution ?
