### ISSUE TITLE
webui tomcat/tornado issues 

### ISSUE THREAD

**Issue by kuberkaul** [bshao001/ChatLearner#41]
So I have now both tornado server and tomcat running and I face two errors. I was hoping you could help out in those:

1. The tornado webserver starts fine  (I dont add papaya.net to my hosts file) but when I try to run 
http://localhost:8080/ChatService?wsdl I get internal server error  (500). The weird thing is this goes away as soon as I switch off my VPN. The error I get with VPN on is : 
```
# Restoring model weights ...
Web service started.
ERROR:tornado.application:Uncaught exception GET /ChatService?wsdl (127.0.0.1)
HTTPServerRequest(protocol='http', host='0.0.0.0:8080', method='GET', uri='/ChatService?wsdl', version='HTTP/1.1', remote_ip='127.0.0.1')
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/tornado/web.py", line 1541, in _execute
    result = method(*self.path_args, **self.path_kwargs)
  File "/home/ec2-user/elian/webui/server/tornadows/soaphandler.py", line 117, in get
    tornado.httpserver.socket.gethostbyname(tornado.httpserver.socket.gethostname()))
socket.gaierror: [Errno -2] Name or service not known
ERROR:tornado.access:500 GET /ChatService?wsdl (127.0.0.1) 5.01ms
```

2. As I run tomcat it spins up the webclient. I enter `Hi` and the webclient fails with 
```
org.apache.jasper.JasperException: Unable to compile class for JSP: 

An error occurred at line: 7 in the jsp file: /ajax/getChatReply.jsp
ChatClient cannot be resolved to a type
4:     response.setContentType("text/html; charset=utf-8");
5:     response.setHeader("Cache-Control", "no-cache");
6: 	
7: 	ChatClient cc = (ChatClient)session.getAttribute("ChatClient");
8:     if (cc == null) {
9: 		cc = new ChatClient("http://papayachat.net:8080/ChatService", 5);
10: 		session.setAttribute("ChatClient", cc);
```
<img width="1155" alt="screen shot 2018-03-27 at 11 21 40 pm" src="https://user-images.githubusercontent.com/2179966/38007286-b82e611c-3216-11e8-90ff-13645a588ae0.png">

Any idea for both the errors?

**Comment by bshao001** [comment]
@kuberkaul 

I cannot be sure. It looks like the first problem is a network related issue. The second one is related to your Java environment: check CLASSPATH for your java runtime.
