### ISSUE TITLE
[Question] How to use custom dataset ?

### ISSUE THREAD

**Issue by aniruddhha** [bshao001/ChatLearner#42]
First thanks a lot for this fantastic repository. This is not an issue, it is just a question. 

1. How should I create custom dataset, what format is needed ?  
2. In which files should I write my custom questions and answers  ?
3. How should I train the bot with custom dataset ?

It would be really great, if you can help me on above questions. 

Thanks in advance.

**Comment by bshao001** [comment]
1. There is not specific format, as long as they appear as pairs, in each of which there should be meaningful relationship (to certain extent) between sentence A and B. It is better that B is always good response as long as A is said, as the model itself does not learn context. You can, however, write multiple A, B, A, B, A, B if these pairs do have certain context. Then separate this whole conversation with the following one using a line "===".

2. Any text file would work. Create a folder under Data/Corpus named temp. When it is done, place it, or multiple files into the temp folder. Then run https://github.com/bshao001/ChatLearner/blob/master/Data/Corpus/preprocesser.py. Check this script, and you will know what I am talking about. After that, you need to run https://github.com/bshao001/ChatLearner/blob/master/Data/Corpus/vocabgenerator.py. Delete vocab.txt before you run this.

3. When the above two steps are done, you can run bottrainer.py to train the model. Remember to create a folder called: Result, under Data folder, if it is not there yet before the training.

**Comment by bshao001** [comment]
@elacsoft That may be normal if your new files do not contain any words outside of existing vocabulary. You can double-check by adding a fake word, such as "addwwyndlkrirhjrlihr4556", into one of the new file, repeating this word a few time. And then check to make sure it appears in the vocab.txt. You can then revert the changes after this experiment.
