### ISSUE TITLE
trained model

### ISSUE THREAD

**Issue by YC-wind** [bshao001/ChatLearner#43]
I am gald to see this fantastic repository.
I encounter a problem, this link (https://drive.google.com/file/d/1mVWFScBHFeA7oVxQzWb8QbKfTi3TToUr/view?usp=sharing) is not available now, so counld you send your trained model to 990800269@qq.com, Thanks a lot!

**Comment by bshao001** [comment]
@YC-wind 
If you are in mainland China and have no access to Google, please try to download the trained model here:

https://pan.baidu.com/s/1flLv8LkrUzlC77j1JXaI2A

**Comment by YC-wind** [comment]
@bshao001 
Thank you very much, It works!
