### ISSUE TITLE
How to add new rules? 

### ISSUE THREAD

**Issue by adithyaChander** [bshao001/ChatLearner#47]
Hello, 
Thank you for creating this wonderful repo. It is really helping me understand how a generative model is built. 
Just a quick question, could you please tell me how to add new rules to your existing model ? 
Thanks.

**Comment by adithyaChander** [comment]
This is more of a question than an issues. I hope it's ok that I have created it as an issue.

**Comment by bshao001** [comment]
@adithyaChander Please refer to the training data in files in this folder: https://github.com/bshao001/ChatLearner/tree/master/Data/Corpus/Augment2. Create rules with specially formatted tags. Then, add the functions into https://github.com/bshao001/ChatLearner/blob/master/chatbot/functiondata.py file. Based on what kind s rules you are trying to add, you might need to do more manipulations.

Hope this helps. BTW, if you do think this repo helped you, please consider star and/or fork it. Thanks.
