### ISSUE TITLE
Resuming chat session 

### ISSUE THREAD

**Issue by nonex1** [bshao001/ChatLearner#49]
Hi, @bshao001 your work has been best, and have encourage me to learn more. 
 Can you please tell me how to save and load the pervious chat session.
For example: 
When I chat with bot and provide my name it will remember name through out the session but once I exit the session it will forget. Is there a way that I can save the chat session and load it back or resume chatting from the previous point .
Thanks before

**Comment by bshao001** [comment]
@nonex1 This is not possible in a randomized HTTP session environment. Instead, if you are trying to build a system that is dedicated to a single user, or a system that has registered users, you can use user ID to identify a session instead. You can then serialize any information in an HTTP session into the file system or database system, and restore the information when the user comes back.

**Comment by nonex1** [comment]
Thanks, @bshao001  totally understood, yes am trying to build personalised chatbot for my self so I that I  can get a better understanding of NLP and deep ML. Just one more thing can you direct me where I can find some information about my query. Thanks Before
