### ISSUE TITLE
cannot run python bottrain.py in chatbot/

### ISSUE THREAD

**Issue by AlexanderYogurt** [bshao001/ChatLearner#5]
no module named "chatbot"

**Comment by AlexanderYogurt** [comment]
So I delete the __main__ part in bottrain.py and add a main.py file under ChatLearner/ with

```
from settings import PROJECT_ROOT
from chatbot.bottrainer import BotTrainer
import os

if __name__ == "__main__":

    corp_dir = os.path.join(PROJECT_ROOT, 'Data', 'Corpus')
    res_dir = os.path.join(PROJECT_ROOT, 'Data', 'Result')
    bt = BotTrainer(corpus_dir=corp_dir)
    bt.train(res_dir)
```

and it works.

**Comment by bshao001** [comment]
@AlexanderYogurt Do you have an environment variable PYTHONPATH setup? It requires this env variable to point to the ChatLearner folder. Please let me know if you have any other issues.

**Comment by AlexanderYogurt** [comment]
Hi thanks. This also works. But since the default search for module begins at the same folder of the .py file you run, is it better to put all the util or model_help folder on the same level with the main script?

I guess it's not important for now since this is not a package to deploy yet, anyway.

**Comment by nggary** [comment]
I face this issue as well, I think this should add to readme

**Comment by mrmrn** [comment]
I used `export PYTHONPATH=$PYTHONPATH:/home/code/ChatLearner/` in linux terminal bot have the error yet and I dont know how to fix it.
