### ISSUE TITLE
None English data

### ISSUE THREAD

**Issue by oma7** [bshao001/ChatLearner#50]
Hi I want to train chatbot in Arabic
should I change the source code for it will work fine?

tnx

**Comment by bshao001** [comment]
For the model part, except the following parts, you don't need to make changes:
1. Encoding. Suggest to use utf-8 encoding.
2. NLTK related code. I am not sure if NLTK supports your language, but you need a tokenizer. You can look for one, or create your own, as long as it is a consistent one in both training and inference processes.
3. The way you tokenize the data may impact the sequence length, and the vocabulary size. As a consequence, you may have to adjust hyper-parameters.

For the rule part, if you need to use, you can refer the idea, but you have to rewrite the details.
