### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by amitguptadumka** [bshao001/ChatLearner#61]
I am getting the following error. Can you help?

 File "C:\Users\amikumar\Desktop\ChatLearner2\chatbot\botpredictor.py", line 50, in __init__
    self.encoder_inputs.append(tf.get_collection("encoder_input{0}".format(i))[0])
IndexError: list index out of range

**Comment by bshao001** [comment]
There is not enough information for me to help with you on this. Thanks.
