### ISSUE TITLE
Does this project supports context of the chat sessions 

### ISSUE THREAD

**Issue by tiru1930** [bshao001/ChatLearner#62]
Hi,
I have came across this project on my web search, It is interesting and well structured, Thank you for sharing this with us. I have few question on this project.

1.Can this project supports context ,i,e multi-turn dialogues?
2.If not What will be the suggested approach to handle multi-turn dialogues? i,e like sending back previous turn response along with current user utterance and having all utterance in memory for each dialogue etc?

Regards
Tiru

**Comment by bshao001** [comment]
Hi, 
I do have a framework that is mainly designed to handle the complicated contexts during the conversations for a chatbot. I am currently working on it, based on the Chinese language (which is much more complex than most other languages regarding context). However, this framework is not open-sourced and only available for business purposes, and it is now used in this project you see.

Thanks for asking.

**Comment by tiru1930** [comment]
Thank you for the response. Will modify this project to handle context as j
required.
