### ISSUE TITLE
Tensorflow version 1.11

### ISSUE THREAD

**Issue by algeorge** [bshao001/ChatLearner#64]
Hello, iam using tensorflow i know this that you mentioned it only support tf 1.4. is there any way i can use tf 1.11?

**Comment by bshao001** [comment]
The implementation here supports TensorFlow 1.4 and later. I tested TF 1.10, but not 1.11. I reviewed the release notes of TF 1.11, and did not see any changes that would break the code. Please try it with TF 1.11, and it should just work without any changes needed. Thanks.

**Comment by algeorge** [comment]
thankyou @bshao001

**Comment by algeorge** [comment]
see below screenshot when i run botui.py
![image](https://user-images.githubusercontent.com/10040170/46993329-5fd73000-d15a-11e8-8b7e-4257c049058d.png)

**Comment by bshao001** [comment]
I have just tested with TensorFlow 1.11, and it works without any problem. Please see the screenshot below.

![botui](https://user-images.githubusercontent.com/26190682/47040935-88a8f680-d155-11e8-95ec-f3c08308e167.png)

**Comment by algeorge** [comment]
are using tf cpu or gpu?

**Comment by algeorge** [comment]
its working!!

Tomcat version 7.0 for web server
i want to add some action function to it like it can open youtube, facebook and play youtube or search on google 
see https://www.youtube.com/watch?v=EPqe8Ayvg7Q&t=385s
thanks alot
