### ISSUE TITLE
请问想看中文的是要钱吗

### ISSUE THREAD

**Issue by ily666666** [bshao001/ChatLearner#66]

**Comment by bshao001** [comment]
本人正在开发的完整中文聊天机器人包括很多私有技术，其核心部分是对聊天中的上下文信息的传递和处理。现有机器人软件在推理时有四个模型同时运行。核心技术部分暂时不公开。

当然您如果想开发最基本的中文聊天机器人（与本开源相当的），本人可以提供少量的免费技术咨询。在此之外，也可以考虑深度的技术合作，付费咨询等其他方式。当然您如果有高质量的中文对话语料，本人也非常愿意付费购买，或者交换部分技术。

谢谢。更过问题请添加本人微信私聊。

**Comment by ily666666** [comment]
噢
