### ISSUE TITLE
botui not picking trained files

### ISSUE THREAD

**Issue by NiranjjanHari** [bshao001/ChatLearner#67]
Hi,

First of all thank you for hosting this project for others to learn.
The bottrainer.py successfully trained and completed 60 epochs and result files were saved in Result folder.
basic-1357.data-00000-of-00001
basic-1357.index
basic-1357.meta
basic-1380.data-00000-of-00001
basic-1380.index
basic-1380.meta
basic-29798.data-00000-of-00001
basic-29798.index
basic-29798.meta
basic-30432.data-00000-of-00001
basic-30432.index
basic-30432.meta
basic-31066.data-00000-of-00001.tempstate17295170149554310043
checkpoint
train_log

But when I execute python botui.py It is unable to pick these files and it is expecting basic.index , please advise what could be wrong.

**Comment by xiaoweiweixiao** [comment]
First, you choose the best trained result from your training result .
Then,you should rename the file name,delete the "-" and the number,only remaining "basic"
for example
 you choose the this result:
    basic-30432.data-00000-of-00001
    basic-30432.index
    basic-30432.meta
you rename the file name,they become this name:
    basic.data-00000-of-00001
    basic.index
After you do this, you will success.
    basic.meta

**Comment by xames3** [comment]
can someone please explain how do I use my own training data?
I'm using Reddit data file of 2015_1
Can someone please tell me the entire steps to create my own training data?
