### ISSUE TITLE
Is there a alternative way to handle functiondata and related corpus? 

### ISSUE THREAD

**Issue by nggary** [bshao001/ChatLearner#7]
In the joke corpus:
Q: Do you know the story of Snow White ?
A: Yes . Here is the story : _func_val_get_story_name_para1_snow_white

There are million of stories in the world, I guess we can not put all of those into corpus. Could we amend  _func_val_get_story_name,  so every time it is called, the function will lookup the user input and use NLP to extract the story name and search from database or else

**Comment by bshao001** [comment]
@nggary If you want to maintain your local database, I think it won't add too much effort by adding the corresponding training samples, except it is not convenient to add training sample gradually (as you will need to train the model again). If you want to retrieve the story online, you can, however, it imposes a lot more burden to the parser. The rules implemented here follow a loose pattern matching idea, which means we will use the model to perform the final pattern matching.

Anyway, if you are interested in that direction, please try it and let me know if you encounter any concrete problems. The goal of the project is just to demo an idea of the integration of a deep learning model with traditional rules.

**Comment by bshao001** [comment]
@nggary Just want to give some concrete examples of why I did not choose the direction you were suggesting. Here are some possible questions:
1. Can you please tell me the story of The Three Little Pigs?
2. Can you please tell me the story of yourself?
3. Can you please tell me the story of your father?
4. Can you please tell me the story of the past?

I think there are way more possibilities, and it would be really challenging to go with that direction.

**Comment by nggary** [comment]
I would like to know if I ask: Could you please tell me the story of Cinderella?
Will the chatbot pass Cinderella as parameter although answer "Yes. Here is the story : _func_val_get_story_name_para1_cinderella" had never trained

**Comment by bshao001** [comment]
@nggary No. If there were no that training sample, the chatbot would not be able  to properly respond that way. As I have explained, your suggestion would work for some other cases as I did for the numbers, but may not work for the story case as demoed in the examples listed above (too hard for the parser). For numbers, there are fixed patterns, therefore, I did it. 

I noticed that you were asking about actions on the deepQA project, and I suggested that is probably doable. You can maintain a list of actions (predefined), and then when your chatbot is asked a question, you analyze the question, and look for any possible actions. If any action is predefined, then replace the question to the way as appeared in the training sample, feed to the model. Your model should then respond with the name of a function. You will then run the function to output the response to answer the question. Check how rule4_arithmetic_ops_new.txt  for details.

**Comment by nggary** [comment]
Thanks for the detail answer, I will try it
