### ISSUE TITLE
Allow Data to be gzipped and predictor to read gzipped data

### ISSUE THREAD

**Issue by sr229** [bshao001/ChatLearner#71]
The recurring problem with this implementation is the Data generated can be too large (~5GB for the pre-trained). I believe we can improve this with application of gzip deflation during data training, and gzip inflation when data is going to be read. 

This will be useful for applications who bases from this that has strict space requirements.

**Comment by bshao001** [comment]
You can check another project of mine: https://github.com/bshao001/TF-Model-Deploy-Tutorial about how to freeze a model for deployment. Thanks.

**Comment by sr229** [comment]
Thanks!
