### ISSUE TITLE
chat service not available at this moment. Please try again later

### ISSUE THREAD

**Issue by ghost** [bshao001/ChatLearner#73]
Hello 
First of all i loved the project which is working perfectly in the console.
But facing an issue while implementing ui.
Now please can anyone help me by resolving this issue where when implemented for the web using the steps as mentioned i get the response as "chat service not available at this moment. Please try again later". The screenshot of it is attached. Speaking server it is running at 5000 port. This i tried with bot API based as well as SOAP service based but both responded me with the same reply.
![chatserviceimage](https://user-images.githubusercontent.com/48402808/54212559-24723f00-4509-11e9-82e5-5cb194a3a3a7.JPG)

**Comment by bshao001** [comment]
For the SOAP option, please first make sure you can see the WSDL on a web browser. This option was for the experienced developers who are used to this approach. In case you are not familiar with this, try the REST option, which is simpler  and more commonly used nowadays.

**Comment by ghost** [comment]
Thanks a lot for your response I’ll check with it and can you please help
me how much time it took for you to train the model that you have uploaded
in the drive link .

**Comment by bshao001** [comment]
With two GTX 1080 Ti GPU cards, it took about 10 hours.

**Comment by ghost** [comment]
Oh thank you
One last help can you please help me to integrate internet to the code like
to fetch the data from internet and display it on the screen

Thank you

**Comment by bshao001** [comment]
Sorry, but I don't understand your question.

**Comment by ghost** [comment]
I just want to ask any question and the relevant answer must be fetched
from the internet like for example
Who is the president of xyz country?
Who is the author of abc book?

It has to scrape through google and answer to these questions

Is it possible to do so ?
Please help me through this

Thank you

**Comment by bshao001** [comment]
This really depends on your application. If you plan to have two types of data input, then you can probably train a binary classification model as the first step, one type of output goes to your second model for response generation using, say, seq2seq, another type of output goes to a module that search for the response from the web. Hope this helps. Thanks.

**Comment by ghost** [comment]
Thanks a lot for your time it truly did helped me a lot
